sudo: false

language: node_js

cache:
  directories:
    - frontend/tests/elm-stuff/build-artifacts
    - sysconfcpus
    - $HOME/.stack

node_js:
  - "5"

before_install:
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - export PATH=/opt/ghc/8.0.1/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - | # epic build time improvement - see https://github.com/elm-lang/elm-compiler/issues/1473#issuecomment-245704142
    if [ ! -d sysconfcpus/bin ];
    then
      git clone https://github.com/obmarg/libsysconfcpus.git;
      cd libsysconfcpus;
      ./configure --prefix=$TRAVIS_BUILD_DIR/sysconfcpus;
      make && make install;
      cd ..;
    fi

install:
  - npm install -g elm@0.17.1
  - npm install -g elm-test@0.17.3
  - mv $(npm config get prefix)/bin/elm-make $(npm config get prefix)/bin/elm-make-old
  - echo "#\!/bin/bash\\n\\necho \"Running elm-make with sysconfcpus -n 2\"\\n\\n$TRAVIS_BUILD_DIR/sysconfcpus/bin/sysconfcpus -n 2 elm-make-old \"\$@\"" > $(npm config get prefix)/bin/elm-make
  - chmod +x $(npm config get prefix)/bin/elm-make

addons:
  apt:
    sources:
      - hvr-ghc
    packages:
      - ghc-8.0.1

before_script:
  - cd frontend/test

script:
  - elm-test AllTests.elm
  - cd ../../backend
  - stack --no-terminal --skip-ghc-check test

deploy:
  - provider: s3
    bucket: confsinfo-elasticbeanstalk
    access_key_id:
      secure: "vvR0ebns9Z72FkgUn2+eQC/jDg+H91zH85onY4rjiCszuajIKa06WbNTmbrUao9FKvAig6IN+rM64A/ii1TR4OF2kN1q7cjFi0/yWi8Xr1Q518wqSR+Ws+rZ5PCptnmBBiPp9cHJ6JgmU3HWy7tDLc5TNfkeuuJRA20sIfukugwW7sNGAnVMhZ6iVQVdRcmjIoCpnEBg6ovTa5S1aUnIt7WVroTpp0OedhXNyUphA4Yu1c9mrb/Yerp7Wnbi5fB+XjMnqa8aAiyJUSkPc6nnW7TDBImQFh9WZqHZE9fX6+BgEQY2dTMJMdRf9xdNtXC0xEiIJu/r1xwWQ4uRZxV6v31/3zVW//YJsIrRwycq7wbCO12Z1qy7zyxfqlBpYbz9/H5ogZAK4PkeGr79ck0JJX+jsqzeE3kQ2jgFM2Elz3W20deyg83JVWAOiZM5xlPAsTtWBY7T70V6Oit72kieDsrwxPg95wnwxwOxXqEKHloMelkjC+9pHp8J/nSVm+mY4BzJKnEXzACHNmZVbgomCWMwaZh3HAUAZ2NOZpfnbCqP8L96U54pJKUTDvCi/QhWAqvR9LIhlWM6plWMTQc6hVs/ZevpIXu0fvG1Y8fcIOxtM7z5as4tcB5dgCbofJU+k7gbvNoNfNtsXMQoYVr3ENXqegsAJz2jc8uQoFW9wAE="
    secret_access_key:
      secure: "M1FDiJEjbKJiuMU9mhs0lGuy7lyPTrP7CoPW9jToPmi/hlVtPpHdMN9xqGs71Cv/bn2dQVN0MK61PuLkgtbvzqxNPrnGpBkoQ/xQLrcKwMSefEFbKEQKXyuA1sNmjI4PxJUw3dGLsQCy0SwzCxXCo3LqOHYmTyKKWbR0/DxYj6JAmaM8X0IUrDFLsB7sjoyWVs/Au4k/h3v2lsqXqZw6+9n4zrmj2zoRDrZkiybr+jK8ROE3114mBWg7bJsUqQfGzbKm59Xosml83NIX44PBg5D7twuLD3QQiMz3ueuB6qsY7FPYQftk1hDSezQ+WK9029u6Gr81Dz8WXUl0SHT5KjmAo/TyNBYNZRLd8W0AIY/5sVDK5ktcbELDMF0dRTxxX7kL0lZb9w6QrjnYW+2U0WoejMhx27dGSMWk4LQSVGq4gQJbEZrhLQ9WEEUlGyFC2fKcn2B26PJ7UPq22sNbKxtYuGHIXMP46xajcbaY/DUX0dVsR4MkOyX7VLrIlhx/KiqbL9RwmK3zcwFGmj/OtGmu9c++VzDJpUcSWAF/dkFkxjRm5rDtNWEQ2cgK5xQSr/Q149pl8XO/ZuQyrK40Zjv4qGIqYh9XeO8EXGX+Zs+tkxoFMsX6cn/Y9EVEwegtlc9uH1dwbmnPNdekiAQ1njGT0B6rAbm3rlhVxJ5Rxcw="
